version: '3.7'
services:
  fozzie:
    build:
      context: ./node
    image: heckler-node:latest
    hostname: fozzie
    volumes:
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /run/lock
      - type: bind
        source: ../
        target: /heckler
    networks:
          heckler:
            ipv4_address: 172.18.0.2
  statler:
    build:
      context: ./node
    image: heckler-node:latest
    hostname: statler
    volumes:
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /run/lock
      - type: bind
        source: ../
        target: /heckler
    networks:
          heckler:
            ipv4_address: 172.18.0.3
  waldorf:
    build:
      context: ./node
    image: heckler-node:latest
    hostname: waldorf
    volumes:
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /run/lock
      - type: bind
        source: ../
        target: /heckler
    networks:
          heckler:
            ipv4_address: 172.18.0.4
  heckler:
    build:
      context: ./node
    image: heckler-node:latest
    hostname: heckler
    volumes:
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /run/lock
      - type: bind
        source: ../
        target: /heckler
    networks:
          heckler:
            ipv4_address: 172.18.0.5
networks:
  heckler:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/24"
